"""empty message

Revision ID: 3dbc20af3c9
Revises: 4d3a316335b
Create Date: 2015-11-17 20:46:32.166943

"""

# revision identifiers, used by Alembic.
revision = '3dbc20af3c9'
down_revision = '4d3a316335b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('singular', sa.String(), nullable=True),
    sa.Column('plural', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('infinitive', sa.String(), nullable=True),
    sa.Column('past_tense', sa.String(), nullable=True),
    sa.Column('present_perfect_tense', sa.String(), nullable=True),
    sa.Column('consonant_change', sa.Boolean(), nullable=True),
    sa.Column('positive', sa.String(), nullable=True),
    sa.Column('comparative', sa.String(), nullable=True),
    sa.Column('superlative', sa.String(), nullable=True),
    sa.Column('adverb', sa.String(), nullable=True),
    sa.Column('conjunction', sa.String(), nullable=True),
    sa.Column('preposition', sa.String(), nullable=True),
    sa.Column('accusative', sa.Boolean(), nullable=True),
    sa.Column('dative', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meaning', sa.String(), nullable=True),
    sa.Column('examples', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('dictionary_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    ### end Alembic commands ###
