"""empty message

Revision ID: 4d3a316335b
Revises: 3d61afdf5f
Create Date: 2015-11-16 19:50:30.299730

"""

# revision identifiers, used by Alembic.
revision = '4d3a316335b'
down_revision = '3d61afdf5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dictionary')
    ### end Alembic commands ###
